In [1]:
import numpy as np

In [2]:
f = open("msaCluster.txt")

In [5]:
def toFloat(seq):
    for x in seq:
        try:
            yield float(x)
        except ValueError:
            yield x

In [54]:
n = 0 
allLists = []

for observation in open("msaCluster.txt"): 
        
    skip = False 

    msa = eval(observation)
    attributes = [] 
    attributes.append(msa[0][0])
    att = list(msa[0][5:])
    attributes.extend(att)
    attributes.extend(list(msa[1]))

    for item in attributes:
        if item == '' or item == 'n': ## remove MSAs with incomplete or unusual datapoints
            skip = True 
            break
        else:
            continue 
    
    if skip: 
        pass
    else:
        attributes = [float(i) for i in attributes]
        allLists.append(np.array(attributes))

In [66]:
msapoints = np.array(allLists)

In [92]:
np.unique(msapoints.T[0])

array([ 2007.,  2008.,  2009.,  2010.,  2011.,  2012.,  2013.])

In [82]:
mins = np.min(msapoints, axis=0)
maxs = np.max(msapoints, axis=0)
rng = maxs - mins

In [83]:
high = 1.0
low = 0.0

In [85]:
scaled_points = high - (((high - low) * (maxs - msapoints)) / rng)

In [89]:
scaled_points.T[0]

array([ 0.66666667,  0.33333333,  0.5       , ...,  0.        ,
        1.        ,  1.        ])

In [93]:
1.00/6.

0.16666666666666666

In [75]:
rawpoints = np.array(
   [[2500, 0.15, 12],
    [1200, 0.65, 20],
    [6200, 0.35, 19]]
) 

In [76]:
high = 1.0
low = 0.0

In [77]:
mins = np.min(rawpoints, axis=0)
maxs = np.max(rawpoints, axis=0)
rng = maxs - mins

In [78]:
scaled_points = high - (((high - low) * (maxs - rawpoints)) / rng)

In [79]:
maxs - rawpoints

array([[  3.70000000e+03,   5.00000000e-01,   8.00000000e+00],
       [  5.00000000e+03,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.00000000e-01,   1.00000000e+00]])

In [80]:
maxs

array([  6.20000000e+03,   6.50000000e-01,   2.00000000e+01])

In [81]:
rawpoints

array([[  2.50000000e+03,   1.50000000e-01,   1.20000000e+01],
       [  1.20000000e+03,   6.50000000e-01,   2.00000000e+01],
       [  6.20000000e+03,   3.50000000e-01,   1.90000000e+01]])